export const LOADING_START = 'LOADING_START'
export const LOADING_STOP = 'LOADING_STOP'

export const FETCH_NEW_ALBUMS_SUCCESS = 'FETCH_NEW_ALBUMS_SUCCESS'

export const UPDATE_SEEN_ALBUMS = 'UPDATE_SEEN_ALBUMS'
